name: pasc
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.19.4
  - openpyxl=3.0.9
  - pandas=1.4.1
  - pillow=8.3.1
  - python=3.9.1
  - readline=8.1
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.1
  - statsmodels=0.12.1
  - tqdm=4.54.1
  - urllib3=1.26.8
  - wheel=0.36.2
  - xlrd=2.0.1
  - pip=20.3.1
  - pip:
    - lifelines==0.26.0
    - lightgbm==3.2.1
    - pyreadstat==1.1.4
    - sas7bdat==2.2.3
    - wrapt==1.12.1
    - xlsxwriter==1.3.8
