python pre_hf_dx.py --dataset wcm 2>&1 | tee  log\pre_hf_dx_wcm.txt
python pre_demo.py --dataset wcm 2>&1 | tee  log\pre_demo_wcm.txt
python pre_hf_dx.py --dataset montefiore 2>&1 | tee  log\pre_hf_dx_montefiore.txt
python pre_demo.py --dataset montefiore 2>&1 | tee  log\pre_demo_montefiore.txt
python pre_hf_dx.py --dataset mshs 2>&1 | tee  log\pre_hf_dx_mshs.txt
python pre_demo.py --dataset mshs 2>&1 | tee  log\pre_demo_mshs.txt
python pre_hf_dx.py --dataset columbia 2>&1 | tee  log\pre_hf_dx_columbia.txt
python pre_demo.py --dataset columbia 2>&1 | tee  log\pre_demo_columbia.txt
python pre_hf_dx.py --dataset nyu 2>&1 | tee  log\pre_hf_dx_nyu.txt
python pre_demo.py --dataset nyu 2>&1 | tee  log\pre_demo_nyu.txt
