#python pre_lab.py --dataset nyu 2>&1 | tee  log\pre_lab_nyu.txt
#python pre_demo.py --dataset nyu 2>&1 | tee  log\pre_demo_nyu.txt
#python pre_covid_lab.py --dataset nyu 2>&1 | tee  log\pre_covid_lab_nyu.txt
#python pre_diagnosis.py --dataset nyu 2>&1 | tee  log/pre_diagnosis_nyu.txt
python pre_medication.py --dataset nyu 2>&1 | tee  log/pre_medication_nyu.txt
python pre_encounter.py --dataset nyu 2>&1 | tee  log/pre_encounter_nyu.txt
python pre_procedure.py --dataset nyu 2>&1 | tee  log/pre_procedure_nyu.txt
python pre_immun.py --dataset nyu 2>&1 | tee  log/pre_immun_nyu.txt
python pre_death.py --dataset nyu 2>&1 | tee  log/pre_death_nyu.txt
python pre_vital.py --dataset nyu 2>&1 | tee  log/pre_vital_nyu.txt
python pre_cohort_manuscript.py --dataset nyu 2>&1 | tee  log/pre_cohort_manuscript_nyu.txt
