python pre_lab.py --dataset mshs 2>&1 | tee  log\pre_lab_mshs.txt
python pre_demo.py --dataset mshs 2>&1 | tee  log\pre_demo_mshs.txt
python pre_covid_lab.py --dataset mshs 2>&1 | tee  log\pre_covid_lab_mshs.txt
python pre_diagnosis.py --dataset mshs 2>&1 | tee  log/pre_diagnosis_mshs.txt
python pre_medication.py --dataset mshs 2>&1 | tee  log/pre_medication_mshs.txt
python pre_encounter.py --dataset mshs 2>&1 | tee  log/pre_encounter_mshs.txt
python pre_procedure.py --dataset mshs 2>&1 | tee  log/pre_procedure_mshs.txt
python pre_immun.py --dataset mshs 2>&1 | tee  log/pre_immun_mshs.txt
python pre_death.py --dataset mshs 2>&1 | tee  log/pre_death_mshs.txt
python pre_vital.py --dataset mshs 2>&1 | tee  log/pre_vital_mshs.txt
python pre_cohort_manuscript.py --dataset mshs 2>&1 | tee  log/pre_cohort_manuscript_mshs.txt
python pre_lab.py --dataset montefiore 2>&1 | tee  log\pre_lab_montefiore.txt
python pre_demo.py --dataset montefiore 2>&1 | tee  log\pre_demo_montefiore.txt
python pre_covid_lab.py --dataset montefiore 2>&1 | tee  log\pre_covid_lab_montefiore.txt
python pre_diagnosis.py --dataset montefiore 2>&1 | tee  log/pre_diagnosis_montefiore.txt
python pre_medication.py --dataset montefiore 2>&1 | tee  log/pre_medication_montefiore.txt
python pre_encounter.py --dataset montefiore 2>&1 | tee  log/pre_encounter_montefiore.txt
python pre_procedure.py --dataset montefiore 2>&1 | tee  log/pre_procedure_montefiore.txt
python pre_immun.py --dataset montefiore 2>&1 | tee  log/pre_immun_montefiore.txt
python pre_death.py --dataset montefiore 2>&1 | tee  log/pre_death_montefiore.txt
python pre_vital.py --dataset montefiore 2>&1 | tee  log/pre_vital_montefiore.txt
python pre_cohort_manuscript.py --dataset montefiore 2>&1 | tee  log/pre_cohort_manuscript_montefiore.txt

